FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.inference.txt ./
RUN pip install --no-cache-dir -r requirements.inference.txt

COPY src ./src
COPY api ./api
COPY Data ./Data
COPY notebooks/xgboost_full_pipeline.pkl ./notebooks/xgboost_full_pipeline.pkl

EXPOSE 8000

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
