FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.inference.txt ./
RUN pip install --no-cache-dir -r requirements.inference.txt

COPY src ./src
COPY streamlit_app.py ./streamlit_app.py
COPY Data ./Data
COPY notebooks/xgboost_full_pipeline.pkl ./notebooks/xgboost_full_pipeline.pkl

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
